#DEV environment

app:
  message: This is the property file to the ${spring.application.name} specific to Dev Environment

spring:
  datasource:
    drive-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa


